-- Initial Schema for cls-sch-pipe

CREATE TABLE SWVPTRM_UR_WEB (
  TERM VARCHAR(6) NOT NULL,
  PTRM VARCHAR(3) NOT NULL, 
  PTRM_DESC VARCHAR(35) NOT NULL, 
  PTRM_START TIMESTAMP NOT NULL, 
  PTRM_END TIMESTAMP NOT NULL,
  PRIMARY KEY (TERM, PTRM)
);

CREATE TABLE SWVSUBJ_WEB (
  TERM VARCHAR(6) NOT NULL,
  PTRM VARCHAR(3) NOT NULL,
  SUBJ VARCHAR(4) NOT NULL,
  SUBJ_DESC VARCHAR(30) NOT NULL,
  PRIMARY KEY (TERM, PTRM, SUBJ)
);

CREATE TABLE SWVAREA_PSPT_WEB (
  AREA VARCHAR(1) NOT NULL,
  AREA_DESC VARCHAR(30) NOT NULL,
  PRIMARY KEY (AREA)
);

CREATE TABLE SWVINST_ASGN_PTRM_WEB (
  TERM VARCHAR(6) NOT NULL,
  PTRM VARCHAR(3) NOT NULL,
  PIDM integer NOT NULL,
  PREF_NAME VARCHAR(120) NOT NULL,
  CA_EMAIL VARCHAR(128),
  PREF_FIRST_NAME VARCHAR(60) NOT NULL,
  PRIMARY KEY (TERM, PTRM, PIDM)
);

CREATE TABLE SWVSPEC_SEARCH_WEB (
  ATTR VARCHAR(4) NOT NULL,
  ATTR_DESC VARCHAR(30) NOT NULL,
  PRIMARY KEY (ATTR)
);

CREATE TABLE SWVCAMP_UR_WEB (
  TERM VARCHAR(6) NOT NULL,
  PTRM VARCHAR(3) NOT NULL,
  CAMP VARCHAR(3) NOT NULL,
  CAMP_DESC VARCHAR(30) NOT NULL,
  PRIMARY KEY (TERM, PTRM, CAMP)
);

CREATE TABLE SWVSECT_WEB (
  CRN VARCHAR(5) NOT NULL,
  SUBJ VARCHAR(4) NOT NULL,
  SUBJ_SEARCH VARCHAR(4) NOT NULL,
  SUBJ_DESC VARCHAR(30) NOT NULL,
  CRSE_NUMB VARCHAR(5) NOT NULL,
  SEQ_NUMB VARCHAR(3) NOT NULL,
  COURSE VARCHAR(14) NOT NULL,
  CRSE_TITLE VARCHAR(35) NOT NULL,
  COURSE_COLL VARCHAR(2) NOT NULL,
  COURSE_COLL_DESC VARCHAR(30) NOT NULL,
  TERM VARCHAR(6) NOT NULL,
  TERM_DESC VARCHAR(30) NOT NULL,
  PTRM VARCHAR(3) NOT NULL,
  SSTS VARCHAR(1) NOT NULL,
  CAMP VARCHAR(3) NOT NULL,
  DAYS VARCHAR(7) NOT NULL,
  MEET_SCHD VARCHAR(3) NOT NULL,
  MEET_TIME VARCHAR(15) NOT NULL,
  INSTRUCT VARCHAR(40) NOT NULL,
  INSTRUCT_ALL VARCHAR(70) NOT NULL,
  INSTRUCT_PRIM VARCHAR(1) NOT NULL,
  PREREQ VARCHAR(200),
  COREQ VARCHAR(255),
  BILL_HRS double precision NOT NULL,
  CAPACITY integer NOT NULL,
  ENRL integer NOT NULL,
  REMAIN integer NOT NULL,
  DATES VARCHAR(11),
  LOCATION VARCHAR(17),
  SESS VARCHAR(1),
  SPECIAL VARCHAR(50),
  SPECIAL_DESC VARCHAR(200),
  TEXT VARCHAR(2500),
  CAPACITY_XLST integer,
  ENRL_XLST integer,
  REMAIN_XLST integer,
  BLDG VARCHAR(6),
  ROOM VARCHAR(10),
  BN_TERM VARCHAR(3),
  CRSE_TEXT VARCHAR(4000),
  PRIMARY KEY (TERM, PTRM, SUBJ, CRSE_NUMB, SEQ_NUMB)
);


